# Generated by Django 5.1.6 on 2025-02-24 08:49

import leave_management.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', leave_management.models.EmployeeManager()),
            ],
        ),
    ]
