# Generated by Django 5.0.1 on 2025-03-06 08:22

from django.db import migrations
from django.utils import timezone

def update_users(apps, schema_editor):
    Employee = apps.get_model('leave_management', 'Employee')
    db_alias = schema_editor.connection.alias
    
    for employee in Employee.objects.using(db_alias).all():
        if not employee.date_of_joining:
            employee.date_of_joining = timezone.now().date()
            employee.save(update_fields=['date_of_joining'])
        
        # Calculate and update experience
        delta = timezone.now().date() - employee.date_of_joining
        Employee.objects.using(db_alias).filter(pk=employee.pk).update(experience=delta.days)

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_employee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RunPython(update_users, reverse_func),
    ]
