# Generated by Django 5.1.6 on 2025-02-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
