# Generated by Django 5.0.1 on 2025-03-06 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_update_existing_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensatoryLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_type', models.CharField(choices=[('INDIVIDUAL', 'Individual Employee'), ('DEPARTMENT', 'Entire Department')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('EEE', 'Electrical and Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('AI', 'Artificial Intelligence'), ('NON_TEACHING', 'Non Teaching'), ('MATH', 'Mathematics'), ('ENGLISH', 'English')], max_length=20, null=True)),
                ('number_of_days', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('granted_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_compensatory_leaves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
