# Generated by Django 5.0.1 on 2025-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_migrate_invalid_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics and Communication'), ('EEE', 'Electrical and Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('AI', 'Artificial Intelligence'), ('NON_TEACHING', 'Non Teaching'), ('MATH', 'Mathematics'), ('ENGLISH', 'English')], default='CSE', max_length=20),
        ),
    ]
