# Generated by Django 5.0.1 on 2025-04-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0008_leaverequest_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
