# Generated by Django 5.0.1 on 2025-04-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0009_alter_holiday_options_alter_holiday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_salary',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
